const envSchema = {
  type: 'object',
  required: [
    'HOSTNAME',
    'PORT',
    'NODE_ENV',
    'ADMIN_API_KEY',
    'PRODUCTION_CORS_ORIGIN',
    'EXTERNAL_API_URL',
    'MYSQL_HOST',
    'MYSQL_PORT',
    'MYSQL_USER',
    'MYSQL_PASSWORD',
    'MYSQL_DB',
    'REDIS_HOST',
    'REDIS_PORT',
    'SESSION_SECRET',
  ],
  properties: {
    HOSTNAME: { type: 'string', minLength: 1 },
    PORT: { type: 'integer', minimum: 1, maximum: 65535 },
    NODE_ENV: { type: 'string', enum: ['development', 'production'] },
    ADMIN_API_KEY: { type: 'string', minLength: 8 },
    PRODUCTION_CORS_ORIGIN: { type: 'string', minLength: 1 },
    EXTERNAL_API_URL: { type: 'string', minLength: 1 },
    MYSQL_HOST: { type: 'string', minLength: 1 },
    MYSQL_PORT: { type: 'integer', minimum: 1, maximum: 65535 },
    MYSQL_USER: { type: 'string', minLength: 1 },
    MYSQL_PASSWORD: { type: 'string' },
    MYSQL_DB: { type: 'string', minLength: 1 },
    REDIS_HOST: { type: 'string', minLength: 1 },
    REDIS_PORT: { type: 'integer', minimum: 1, maximum: 65535 },
    SESSION_SECRET: { type: 'string', minLength: 32 },
  },
  additionalProperties: true,
};

export { envSchema };
