services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      MYSQL_HOST: mysql
      REDIS_HOST: redis
    ports:
      - '3000:3000'
